name: deploy lambda function
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkoutcode
	uses: actions/checkout@v2
      - name: setuppython
	uses: actions/setup-python@v2
	with
	  python-version: 3.8
      - name: install libraries 
	run: |
            cd function
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
      - name: zip bundle
	run: |
	    cd function
	    zip -r ../${{ github.sha }}.zip .
      - name: archive artifact
	uses: actions/upload-artifact@v2
	with
          name: zipped-bundle
	  path: ${{ github.sha }}.zip
	  
